services:
  web:
    image: web
    build: 
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - type: bind
        source: "./app"
        target: "/app"
    tty: true