# 参考: https://qiita.com/Jazuma/items/aca397e081a7825d0dec
name: Build And Push Container Image

on:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rust-scraper
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # イメージをプッシュする権限をGITHUB_TOKENに付与する
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # 1. ghcrにログインする
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # 2. コンテナイメージをビルド・pushする
    - name: Build and Push Container
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} 